name: build_windows

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - name: Build
        run: |
          cd src
          $msbuild = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Msbuild\Current\Bin\MSBuild.exe"
          $a = @("muscle.sln", "/p:Platform=x64", "/p:Configuration=Release")
          & $msbuild $a
          
      - name: Upload binary artifact
        uses: actions/upload-artifact@v2
        with:
          name: muscle-windows-exe
          path: src/x64/Release/muscle.exe
